openapi: 3.0.0

info:
  title: API Refuge de chats
  description: API REST – Projet Dev Web 3
  version: 1.0.0

servers:
  - url: https://refugedechat-csgthcd9dqc8cmdr.canadacentral-01.azurewebsites.net/api

tags:
  - name: Auth
  - name: Chats
  - name: Users

paths:

  /auth/generatetoken:
    post:
      tags:
        - Auth
      summary: Générer un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Token généré avec succès

  /chats:
    get:
      tags:
        - Chats
      summary: Récupérer tous les chats (avec filtres)
      parameters:
        - in: query
          name: race
          required: false
          schema:
            type: string
          description: Filtrer par race du chat
        - in: query
          name: tauxEnergie
          required: false
          schema:
            type: number
            minimum: 1
            maximum: 5
          description: Filtrer par taux d’énergie
      responses:
        '200':
          description: Liste des chats

  /chats/add:
    post:
      tags:
        - Chats
      summary: Ajouter un chat
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
      responses:
        '201':
          description: Chat créé avec succès

  /chats/{id}:
    get:
      tags:
        - Chats
      summary: Récupérer un chat par ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Chat trouvé
        '404':
          description: Chat non trouvé

    put:
      tags:
        - Chats
      summary: Modifier un chat
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
      responses:
        '200':
          description: Chat modifié avec succès

    delete:
      tags:
        - Chats
      summary: Supprimer un chat
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Chat supprimé avec succès

  /users:
    get:
      tags:
        - Users
      summary: Récupérer tous les utilisateurs
      responses:
        '200':
          description: Liste des utilisateurs

    post:
      tags:
        - Users
      summary: Ajouter un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Utilisateur créé avec succès

    put:
      tags:
        - Users
      summary: Modifier un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Utilisateur modifié avec succès

  /users/{email}:
    delete:
      tags:
        - Users
      summary: Supprimer un utilisateur
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Utilisateur supprimé avec succès

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    User:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string

    Chat:
      type: object
      required:
        - nom
        - race
        - numeroDossier
        - dateNaissance
        - tauxEnergie
        - sociabiliteHumain
        - compatEnfants
        - compatChiens
        - compatChats
        - description
        - micropuce
        - sterilise
        - vaccinsBase
      properties:
        nom:
          type: string
        race:
          type: string
        numeroDossier:
          type: number
        dateNaissance:
          type: string
          format: date
        tauxEnergie:
          type: number
          minimum: 1
          maximum: 5
        sociabiliteHumain:
          type: number
          minimum: 1
          maximum: 5
        compatEnfants:
          type: number
          minimum: 1
          maximum: 5
        compatChiens:
          type: number
          minimum: 1
          maximum: 5
        compatChats:
          type: number
          minimum: 1
          maximum: 5
        description:
          type: string
        micropuce:
          type: boolean
        sterilise:
          type: boolean
        vaccinsBase:
          type: boolean
        photos:
          type: array
          items:
            type: string
